version: 2

workflows:
  version: 2
  test_n_deploy:
    jobs:
      - test-node8
#          requires:
#            - test-linter

#      - build-docs:
#          requires:
#            - test-node6
#            - test-node8

      - test-linter

jobs:
  test-node8: &test-template
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run:
          name: Install build tools
          command: sudo yarn global add codecov yalc

      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}

      - run:
          name: Add the entire ICU (full-icu) 1
          command: npm install full-icu

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Add the entire ICU (full-icu) 2
          command: npm install full-icu

      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
              - node_modules

      - run: node --icu-data-dir=node_modules/full-icu scripts/test.js

      - run:
          name: Send coverage report
          command: |
              if [ "${NODEJS}" == "4" ]; then
                codecov
              fi

      - store_test_results:
          path: ./results/
          when: always

#  test-node6:
#    <<: *test-template
#
#    docker:
#      - image: circleci/node:6

  test-linter:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout

      - run:
          name: Install build tools
          command: sudo yarn global add codecov yalc

      - restore_cache:
          key: node-modules-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          key: node-modules-{{ checksum "yarn.lock" }}
          paths:
              - node_modules

      - run: yarn run lint

  build-docs:
    docker:
      - image: circleci/python:latest
        environment:
          PYGMENTS_NODE_COMMAND: /usr/local/bin/node

    steps:
      - checkout

      - run: sudo pip install pipenv

      - restore_cache:
          key: pipenv-{{ checksum "Pipfile.lock" }}

      - run: pipenv install

      - save_cache:
          key: pipenv-{{ checksum "Pipfile.lock" }}
          paths:
              - "{{ pipenv --venv }}"

      - run: cd docs && pipenv run make html

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./scripts/deploy-docs.sh
            fi
